# 像素地物映射值
ICE_VALUE = 2
NODATA_VALUE = 255
OUTPUT_NODATA = -9999

# 空间物候算法参数
CHECK_WINDOW = 30       # 窗口长度 30天
TOLERANCE_NOISE = 7     # 容错天数 7天

# 阈值定义 (FU判定: 前30天冰<=7, 后30天冰>=23)
THRESHOLD_LOW = TOLERANCE_NOISE
THRESHOLD_HIGH = CHECK_WINDOW - TOLERANCE_NOISE
